[package]
name = "lep2p-transport"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
lep2p-identity.workspace = true
lep2p-core.workspace = true
lep2p-obfs.workspace = true
lep2p-e2ee.workspace = true
rustls = { version = "0.23", default-features = false, features = ["ring", "std"] }
tokio.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
quinn = { version = "0.11", default-features = false, features = ["ring", "runtime-tokio", "rustls"] }
quinn-proto = "0.11"
h3 = "=0.0.7"
h3-quinn = "0.0.8"
http = "1"
bytes = "1"
async-trait = "0.1"
futures = "0.3"
thiserror = "2"

[dev-dependencies]
sha2 = "0.10"
async-trait = "0.1"
